<section id="Breadcrumb" class="firstSection nopadding">
	<div class="container">
		<div class="row">
			<ul>
				<li class="bread">
					<a href="#">INICIO</a>
				</li>
				<li class="bread">
					<a href="#">PRODUCTOS</a>
				</li>
				<li class="bread">
					<a href="#">BOTELLAS</a>
				</li>
				<li class="bread">
					<a href="#">1ml - 49 ml</a>
				</li>
				<li class="search">
					<input type="text" placeholder="BUSCAR">
					<svg version="1.1" id="Capa_1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px" viewBox="0 0 17 17" style="enable-background:new 0 0 17 17;" xml:space="preserve">
						<path d="M16.5,16.5c-0.6,0.6-1.6,0.6-2.3,0l-2.8-2.8c-1.2,0.7-2.5,1.2-4,1.2C3.3,14.9,0,11.6,0,7.5S3.3,0,7.5,0c4.1,0,7.5,3.3,7.5,7.5c0,1.5-0.4,2.8-1.2,4l2.8,2.8C17.2,14.9,17.2,15.9,16.5,16.5z M7.5,2.1c-2.9,0-5.3,2.4-5.3,5.3s2.4,5.3,5.3,5.3c2.9,0,5.3-2.4,5.3-5.3C12.8,4.5,10.4,2.1,7.5,2.1z"/>
					</svg>
				</li>
			</ul>
		</div>
	</div>
</section>

<section id="detalle">
	<div class="container">
		<div class="row">
			<div class="col-xs-12 nopadding">
				<div class="col-xs-12 col-sm-6">
					<div class="col-xs-12 nopadding slideDetalleZoom">
						<div class="col-xs-12 nopadding item">
							<img src="assets/img/productos/producto1.png" alt="">
						</div>
						<div class="col-xs-12 nopadding item">
							<img src="assets/img/productos/producto2.png" alt="">
						</div>
						<div class="col-xs-12 nopadding item">
							<img src="assets/img/productos/producto3.png" alt="">
						</div>
						<div class="col-xs-12 nopadding item">
							<img src="assets/img/productos/producto4.png" alt="">
						</div>
						<div class="col-xs-12 nopadding item">
							<img src="assets/img/productos/producto5.png" alt="">
						</div>
					</div>
					<div class="col-xs-12 nopadding slideDetalleThumbs">
						<div class="col-xs-12 nopadding item">
							<img src="assets/img/productos/producto1.png" alt="">
						</div>
						<div class="col-xs-12 nopadding item">
							<img src="assets/img/productos/producto2.png" alt="">
						</div>
						<div class="col-xs-12 nopadding item">
							<img src="assets/img/productos/producto3.png" alt="">
						</div>
						<div class="col-xs-12 nopadding item">
							<img src="assets/img/productos/producto4.png" alt="">
						</div>
						<div class="col-xs-12 nopadding item">
							<img src="assets/img/productos/producto5.png" alt="">
						</div>
					</div>
				</div>
				<div class="col-xs-12 col-sm-6 text-left info">
					<h2 class="textPurppleShin bold nomargin">Silueta 250 ml</h2>
					<h4 class="textGrey light nomargin">CLAVE: 1232</h4>
					<span class="spanStock">EN STOCK</span>
					<div class="col-xs-12 noHorizontalPadding vpadding">
						<div class="col-xs-12 col-sm-8 col-md-7 col-lg-6 nopadding">
							<div class="col-xs-12 nopadding text">
								<span>Rosca</span>
								<span>24/415</span>
							</div>
							<div class="col-xs-12 nopadding text">
								<span>Clave</span>
								<span>1238</span>
							</div>
							<div class="col-xs-12 nopadding text">
								<span>Altura</span>
								<span>172 mm</span>
							</div>
							<div class="col-xs-12 nopadding text">
								<span>Pzas/caja</span>
								<span>159</span>
							</div>
						</div>
					</div>
					<p class="col-xs-12 noHorizontalPadding vpadding nopaddingTop nomargin">
						Botella ovalada en color cristal hecha en PET liviano y resistente a los impactos. 
					</p>
					<p class="col-xs-12 nopadding nomargin">Venta mínima</p>
					<p class="col-xs-12 nopadding nomargin">1 caja en color cristal</p>
					<p class="col-xs-12 nopadding nomargin">Resurtido constante</p>
					<p class="col-xs-12 nopadding nomargin">10,000 pzas en botella de color</p>
					<p class="col-xs-12 nopadding nomargin">Bajo pedido</p>
					<p class="col-xs-12 noHorizontalPadding vpadding nopaddingBottom nomargin"><strong>Otros tamaños</strong></p>
					<p class="col-xs-12 nopadding nomargin">30 ml, 50 ml, 75 ml, 125 ml, 500 ml, 1,000 ml</p>
					<div class="col-xs-12 noHorizontalPadding vpadding">
						<a href="#" class="btnCotizar" tabindex="0">
							<span>COTIZAR</span>
							<svg version="1.1" id="Capa_1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px" viewBox="0 0 189.6 184.2" style="enable-background:new 0 0 189.6 184.2;" xml:space="preserve">
								<path d="M173,161.3c0-12.6-10.3-22.9-22.9-22.9c-12.6,0-22.9,10.3-22.9,22.9c0,12.6,10.2,22.9,22.9,22.9C162.7,184.2,172.9,174,173,161.3z M143.1,161.3c0-3.8,3.1-6.9,6.9-6.9s6.9,3.1,6.9,6.9s-3.1,6.9-6.9,6.9h0C146.2,168.2,143.2,165.1,143.1,161.3z"></path>
								<path d="M43.6,100.3c-7.3,9.2-5.8,22.6,3.4,29.9c3.8,3,8.5,4.7,13.3,4.6h109.4v-16H60.2c-2.9,0-5.3-2.4-5.3-5.3c0-2.9,2.4-5.3,5.3-5.3H170L189.6,29H42.9L36,0H0v16h23.4L43.6,100.3z M169.2,45l-11.7,47.3H58.1L46.8,45L169.2,45z"></path>
								<path d="M60.4,184.2c12.6,0,22.9-10.3,22.9-22.9c0-12.6-10.3-22.9-22.9-22.9c-12.6,0-22.9,10.3-22.9,22.9C37.5,174,47.8,184.2,60.4,184.2z M60.4,154.4c3.8,0,6.9,3.1,6.9,6.9c0,3.8-3.1,6.9-6.9,6.9c-3.8,0-6.9-3.1-6.9-6.9l0,0C53.5,157.5,56.6,154.4,60.4,154.4L60.4,154.4z"></path>
							</svg>
						</a>
					</div>
					<p class="col-xs-12 nopadding nomargin">Compartir</p>
					<ul class="share">
            		  <li>
            		    <a href="#">
            		      <svg version="1.1" id="Capa_1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px" viewBox="0 0 43.9 43.9" style="enable-background:new 0 0 43.9 43.9;" xml:space="preserve">
            		        <path d="M22,0C9.8,0,0,9.8,0,22c0,12.1,9.8,22,22,22c12.1,0,22-9.8,22-22C43.9,9.8,34.1,0,22,0z M31.6,18c0,0.2,0,0.4,0,0.6c0,6.5-5,14.1-14.1,14.1c-2.8,0-5.4-0.8-7.6-2.2c0.4,0,0.8,0.1,1.2,0.1c2.3,0,4.4-0.8,6.1-2.1c-2.2,0-4-1.5-4.6-3.4c0.3,0.1,0.6,0.1,0.9,0.1c0.5,0,0.9-0.1,1.3-0.2c-2.3-0.5-4-2.5-4-4.8c0,0,0,0,0-0.1c0.7,0.4,1.4,0.6,2.2,0.6c-1.3-0.9-2.2-2.4-2.2-4.1c0-0.9,0.2-1.8,0.7-2.5c2.4,3,6.1,5,10.2,5.2c-0.1-0.4-0.1-0.7-0.1-1.1c0-2.7,2.2-4.9,4.9-4.9c1.4,0,2.7,0.6,3.6,1.6c1.1-0.2,2.2-0.6,3.1-1.2c-0.4,1.2-1.2,2.1-2.2,2.7c1-0.1,2-0.4,2.8-0.8C33.4,16.4,32.5,17.3,31.6,18z"></path>
            		      </svg>
            		    </a>
            		  </li>
            		  <li>
            		    <a href="#">
            		      <svg version="1.1" id="Capa_1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px" viewBox="0 0 43.9 43.9" style="enable-background:new 0 0 43.9 43.9;" xml:space="preserve">
            		        <path d="M22.1,0.9c-11.8,0-21.4,9.6-21.4,21.4c0,11.8,9.6,21.4,21.4,21.4c11.8,0,21.4-9.6,21.4-21.4C43.5,10.5,33.9,0.9,22.1,0.9z M27.7,22.3h-3.6v13.1h-5.4V22.3H16v-4.5h2.7v-2.7c0-3.7,1.5-5.9,5.9-5.9h3.6v4.5h-2.3c-1.7,0-1.8,0.6-1.8,1.8l0,2.3h4.1L27.7,22.3z"></path>
            		      </svg>
            		    </a>
            		  </li>
            		  <li>
            		    <a href="#">
            		      <svg version="1.1" id="Capa_1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px" viewBox="0 0 43.9 43.9" style="enable-background:new 0 0 43.9 43.9;" xml:space="preserve">
            		        <g>
            		          <path d="M16.3,24.7c-2.7,0-5.1,1.7-5.1,3.7c0,2.1,2,3.8,4.7,3.8c3.8,0,5.1-1.6,5.1-3.7c0-0.2,0-0.5-0.1-0.7c-0.3-1.2-1.4-1.7-2.8-2.8C17.5,24.8,16.9,24.7,16.3,24.7z"></path>
            		          <path d="M22.1,0.5c-11.8,0-21.4,9.6-21.4,21.4c0,11.8,9.6,21.4,21.4,21.4c11.8,0,21.4-9.6,21.4-21.4C43.6,10.1,34,0.5,22.1,0.5z M21.8,15.7c0,1.5-0.8,2.8-2,3.7c-1.1,0.9-1.4,1.3-1.4,2c0,0.6,1.2,1.7,1.9,2.2c1.9,1.3,2.5,2.5,2.5,4.6c0,2.6-2.5,5.1-6.9,5.1c-3.9,0-7.2-1.6-7.2-4.2c0-2.6,3-5.1,6.9-5.1c0.4,0,0.8,0,1.2,0c-0.5-0.5-1-1.2-1-2c0-0.5,0.1-0.9,0.4-1.3c-0.2,0-0.4,0-0.7,0c-3.2,0-5.4-2.3-5.4-5.1c0-2.8,3-5.2,6.2-5.2h7.1l-1.6,1.1h-2.2C21,12.2,21.8,13.9,21.8,15.7z M35.6,16.5h-4.3v4.3h-1.7v-4.3h-4.3v-1.7h4.3v-4.3h1.7v4.3h4.3V16.5z"></path>
            		          <path d="M15.4,11.5c-1.8-0.1-3,1.8-2.7,4.2c0.3,2.4,2,4.4,3.9,4.4c1.8,0.1,3-1.8,2.7-4.2C19,13.5,17.2,11.6,15.4,11.5z"></path>
            		        </g>
            		      </svg>
            		    </a>
            		  </li>
            		</ul>
				</div>
			</div>
		</div>
	</div>
</section>

<section id="tapasSugeridas" class="nopaddingTop">
	<div class="container">
		<div class="row">
			<div class="col-xs-12 col-sm-6 nopadding text-left">
				<h3 class="col-xs-12 noHorizontalPadding vpadding nopaddingTop textPurppleShin light">TAPAS SUGERIDAS</h3>
				<div class="col-xs-12 grayContainer">
					<div class="col-xs-3 item text-center">
						<div class="col-xs-12 nopadding centered">
							<div class="col-xs-12 nopadding image">
								<img src="assets/img/tapas/1.png" alt="">
							</div>
							<h5 class="col-xs-12 noHorizontalPadding vpadding nomargin tittle textPurppleShin">
								TAPA NOMBRE
							</h5>
							<div class="col-xs-12 nopadding text-center">
								<a href="#" class="addToCart centered">
									<img src="assets/img/cart.svg" alt="">
								</a>
							</div>
						</div>
					</div>
					<div class="col-xs-3 item text-center">
						<div class="col-xs-12 nopadding centered">
							<div class="col-xs-12 nopadding image">
								<img src="assets/img/tapas/2.png" alt="">
							</div>
							<h5 class="col-xs-12 noHorizontalPadding vpadding nomargin tittle textPurppleShin">
								TAPA NOMBRE
							</h5>
							<div class="col-xs-12 nopadding text-center">
								<a href="#" class="addToCart centered">
									<img src="assets/img/cart.svg" alt="">
								</a>
							</div>
						</div>
					</div>
					<div class="col-xs-3 item text-center">
						<div class="col-xs-12 nopadding centered">
							<div class="col-xs-12 nopadding image">
								<img src="assets/img/tapas/3.png" alt="">
							</div>
							<h5 class="col-xs-12 noHorizontalPadding vpadding nomargin tittle textPurppleShin">
								TAPA NOMBRE
							</h5>
							<div class="col-xs-12 nopadding text-center">
								<a href="#" class="addToCart centered">
									<img src="assets/img/cart.svg" alt="">
								</a>
							</div>
						</div>
					</div>
					<div class="col-xs-3 item text-center">
						<div class="col-xs-12 nopadding centered">
							<div class="col-xs-12 nopadding image">
								<img src="assets/img/tapas/4.png" alt="">
							</div>
							<h5 class="col-xs-12 noHorizontalPadding vpadding nomargin tittle textPurppleShin">
								TAPA NOMBRE
							</h5>
							<div class="col-xs-12 nopadding text-center">
								<a href="#" class="addToCart centered">
									<img src="assets/img/cart.svg" alt="">
								</a>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</section>

<section id="otrosTamaños" class="nopaddingTop">
	<div class="container">
		<div class="row">
			<div class="col-xs-12 col-sm-6 nopadding text-left">
				<h3 class="col-xs-12 noHorizontalPadding vpadding nopaddingTop textPurppleShin light">TAPAS SUGERIDAS</h3>
				<div class="col-xs-12">
					<img src="assets/img/tamaños.jpg" alt="" class="col-xs-12 nopadding">
				</div>
			</div>
		</div>
	</div>
</section>
