<section id="footer">
  <div class="vertical start">
    <div class="col-xs-12 nopadding text-center">
      <a href="#Top" class="top scrollTo">
        <svg class="bounce-sm" version="1.1" xmlns:cc="http://creativecommons.org/ns#" xmlns:dc="http://purl.org/dc/elements/1.1/" xmlns:inkscape="http://www.inkscape.org/namespaces/inkscape" xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#" xmlns:sodipodi="http://sodipodi.sourceforge.net/DTD/sodipodi-0.dtd" xmlns:svg="http://www.w3.org/2000/svg" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px" viewBox="0 0 104 60" style="enable-background:new 0 0 104 60;" xml:space="preserve">
          <g transform="translate(0,-952.36218)">
            <path class="st0" d="M52,952.4l-52,42v18l52-42l52,42v-18L52,952.4z"></path>
          </g>
        </svg>
      </a>
    </div>
  </div>
  <div class="container">
    <div class="row">
      <div class="col-xs-12 nopadding text-left">
        <div class="col-xs-12 col-sm-3 text-center">
          <img src="assets/img/logoFooter.svg" alt="" class="logoFooter">
        </div>
        <div class="col-xs-12 col-sm-3">
          <h3 class="col-xs-12 nopadding textPurpple text-center">CONTACTO</h3>
          <ul class="contact">
            <li>
              <svg version="1.1" id="Capa_1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px" viewBox="0 0 13.9 14.3" style="enable-background:new 0 0 13.9 14.3;" xml:space="preserve">
                <g>
                  <g>
                    <path d="M9.4,10l4,1.8c0,0,0-0.6,0-0.9c0-0.2,0-0.4-0.2-0.5c-0.2-0.1-2.3-1-2.5-1.1c-0.2-0.1-0.6,0-0.7,0.1C10,9.5,9.4,10,9.4,10z"/>
                  </g>
                  <g>
                    <path d="M4.4,4.6l-1.2-4c0,0,1.1-0.2,1.3,0.4c0,0,0.6,2,0.7,2.6C5.5,4.2,4.4,4.6,4.4,4.6z"/>
                  </g>
                  <g>
                    <path d="M9.2,10.4l3.9,1.7c0,0-1.2,1.3-2.5,1.7c-3,0.8-6.7-2.9-7.4-3.9c-0.8-1-4-6.1-2.1-8.1C1.8,1,2.9,0.7,2.9,0.7l1.2,4c0,0-1,0.9-0.1,2c0.9,1.1,2.5,2.9,3.4,3.7C8.4,11.3,9.2,10.4,9.2,10.4z"/>
                  </g>
                </g>
              </svg>
              <a href="#">01 (55) 5649 8005 (10 líneas)</a>
            </li>
            <li>
              <svg version="1.1" id="Capa_1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px" viewBox="0 0 13.9 14.3" style="enable-background:new 0 0 13.9 14.3;" xml:space="preserve">
                <g>
                  <path class="st0" d="M6.9,0.5c-3.6,0-6.5,2.9-6.5,6.5s2.9,6.5,6.5,6.5s6.5-2.9,6.5-6.5S10.5,0.5,6.9,0.5z M6.9,12.1c-2.9,0-5.2-2.3-5.2-5.2s2.3-5.2,5.2-5.2s5.2,2.3,5.2,5.2S9.8,12.1,6.9,12.1z"/>
                  <path class="st0" d="M7.3,3.7h-1v3.9l3.4,2l0.5-0.8L7.3,7.1L7.3,3.7z"/>
                </g>
              </svg>
              <a href="#">Lunes a Viernes. 9:00 am a 5:00 pm.</a>
            </li>
            <li>
              <svg version="1.1" id="Capa_1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px" viewBox="0 0 13.9 14.3" style="enable-background:new 0 0 13.9 14.3;" xml:space="preserve">
                <path class="st0" d="M0.5,2.9v8.7h13.1V2.9H0.5z M7,7.6L1.5,3.4h11.1L7,7.6z M1,11V3.8l3.9,3L2.6,9.4l0.1,0.1l2.7-2.4L7,8.3l1.6-1.2l2.7,2.4l0.1-0.1L9.1,6.7l3.9-3V11H1z"/>
              </svg>
              <a href="#">ventas@escowill.com.mx</a>
            </li>
            <li>
              <svg version="1.1" id="Capa_1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px" viewBox="0 0 13.9 14.3" style="enable-background:new 0 0 13.9 14.3;" xml:space="preserve">
                <g>
                  <path class="st0" d="M6.9,6c1,0,1.8-0.8,1.8-1.8c0-1-0.8-1.8-1.8-1.8S5.1,3.2,5.1,4.2c0,0,0,0,0,0C5.1,5.2,5.9,6,6.9,6z"/>
                  <path class="st0" d="M12.6,8.3c0-0.2-0.2-0.4-0.4-0.4H9.4L10,7.1c0.6-0.8,0.9-1.8,0.9-2.8c-0.1-2.2-1.9-3.9-4.1-3.9S2.9,2.1,2.7,4.3c-0.1,1,0.2,2,0.9,2.8l0.6,0.8H1.5C1.3,7.9,1.1,8,1.1,8.3l-0.9,4.9c0,0.2,0.1,0.5,0.4,0.5c0,0,0.1,0,0.1,0h12.5c0.2,0,0.4-0.2,0.4-0.4c0,0,0-0.1,0-0.1L12.6,8.3z M3.6,4.4C3.7,2.9,5,1.3,6.8,1.3S9.9,2.9,10,4.4c0,0.8-0.2,1.6-0.7,2.2L6.8,9.9L4.3,6.6C3.8,5.9,3.6,5.2,3.6,4.4L3.6,4.4z M1.1,12.8l0.7-4h3l1.6,2.1c0.1,0.2,0.4,0.2,0.6,0.1c0,0,0.1-0.1,0.1-0.1l1.6-2.1h3.1l0.7,4H1.1z"/>
                </g>
              </svg>
              <a href="#">Azafrán No. 339 Col Granjas México, Iztacalco, Ciudad de México C.P. 08400</a>
            </li>
          </ul>
        </div>
        <div class="col-xs-12 col-sm-3">
          <h3 class="col-xs-12 nopadding textPurpple text-center">SUCURSALES</h3>
          <ul class="sucursales">
            <li>
              <a href="#">CIUDAD DE MÉXICO</a>
            </li>
            <li>
              <a href="#">GUADALAJARA</a>
            </li>
            <li>
              <a href="#">MONTERREY</a>
            </li>
            <li>
              <a href="#">QUERÈTARO</a>
            </li>
          </ul>
        </div>
        <div class="col-xs-12 col-sm-3">
          <h3 class="col-xs-12 nopadding textPurpple text-center">SíGUENOS EN</h3>
          <div class="col-xs-12 nopadding text-center">
            <ul class="social centered">
              <li>
                <a href="#">
                  <svg version="1.1" id="Capa_1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px" viewBox="0 0 43.9 43.9" style="enable-background:new 0 0 43.9 43.9;" xml:space="preserve">
                    <path d="M22,0C9.8,0,0,9.8,0,22c0,12.1,9.8,22,22,22c12.1,0,22-9.8,22-22C43.9,9.8,34.1,0,22,0z M31.6,18c0,0.2,0,0.4,0,0.6c0,6.5-5,14.1-14.1,14.1c-2.8,0-5.4-0.8-7.6-2.2c0.4,0,0.8,0.1,1.2,0.1c2.3,0,4.4-0.8,6.1-2.1c-2.2,0-4-1.5-4.6-3.4c0.3,0.1,0.6,0.1,0.9,0.1c0.5,0,0.9-0.1,1.3-0.2c-2.3-0.5-4-2.5-4-4.8c0,0,0,0,0-0.1c0.7,0.4,1.4,0.6,2.2,0.6c-1.3-0.9-2.2-2.4-2.2-4.1c0-0.9,0.2-1.8,0.7-2.5c2.4,3,6.1,5,10.2,5.2c-0.1-0.4-0.1-0.7-0.1-1.1c0-2.7,2.2-4.9,4.9-4.9c1.4,0,2.7,0.6,3.6,1.6c1.1-0.2,2.2-0.6,3.1-1.2c-0.4,1.2-1.2,2.1-2.2,2.7c1-0.1,2-0.4,2.8-0.8C33.4,16.4,32.5,17.3,31.6,18z"/>
                  </svg>
                </a>
              </li>
              <li>
                <a href="#">
                  <svg version="1.1" id="Capa_1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px" viewBox="0 0 43.9 43.9" style="enable-background:new 0 0 43.9 43.9;" xml:space="preserve">
                    <path d="M22.1,0.9c-11.8,0-21.4,9.6-21.4,21.4c0,11.8,9.6,21.4,21.4,21.4c11.8,0,21.4-9.6,21.4-21.4C43.5,10.5,33.9,0.9,22.1,0.9z M27.7,22.3h-3.6v13.1h-5.4V22.3H16v-4.5h2.7v-2.7c0-3.7,1.5-5.9,5.9-5.9h3.6v4.5h-2.3c-1.7,0-1.8,0.6-1.8,1.8l0,2.3h4.1L27.7,22.3z"/>
                  </svg>
                </a>
              </li>
              <li>
                <a href="#">
                  <svg version="1.1" id="Capa_1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px" viewBox="0 0 43.9 43.9" style="enable-background:new 0 0 43.9 43.9;" xml:space="preserve">
                    <g>
                      <path d="M16.3,24.7c-2.7,0-5.1,1.7-5.1,3.7c0,2.1,2,3.8,4.7,3.8c3.8,0,5.1-1.6,5.1-3.7c0-0.2,0-0.5-0.1-0.7c-0.3-1.2-1.4-1.7-2.8-2.8C17.5,24.8,16.9,24.7,16.3,24.7z"/>
                      <path d="M22.1,0.5c-11.8,0-21.4,9.6-21.4,21.4c0,11.8,9.6,21.4,21.4,21.4c11.8,0,21.4-9.6,21.4-21.4C43.6,10.1,34,0.5,22.1,0.5z M21.8,15.7c0,1.5-0.8,2.8-2,3.7c-1.1,0.9-1.4,1.3-1.4,2c0,0.6,1.2,1.7,1.9,2.2c1.9,1.3,2.5,2.5,2.5,4.6c0,2.6-2.5,5.1-6.9,5.1c-3.9,0-7.2-1.6-7.2-4.2c0-2.6,3-5.1,6.9-5.1c0.4,0,0.8,0,1.2,0c-0.5-0.5-1-1.2-1-2c0-0.5,0.1-0.9,0.4-1.3c-0.2,0-0.4,0-0.7,0c-3.2,0-5.4-2.3-5.4-5.1c0-2.8,3-5.2,6.2-5.2h7.1l-1.6,1.1h-2.2C21,12.2,21.8,13.9,21.8,15.7z M35.6,16.5h-4.3v4.3h-1.7v-4.3h-4.3v-1.7h4.3v-4.3h1.7v4.3h4.3V16.5z"/>
                      <path d="M15.4,11.5c-1.8-0.1-3,1.8-2.7,4.2c0.3,2.4,2,4.4,3.9,4.4c1.8,0.1,3-1.8,2.7-4.2C19,13.5,17.2,11.6,15.4,11.5z"/>
                    </g>
                  </svg>
                </a>
              </li>
              <li>
                <a href="#">
                  <svg version="1.1" id="Capa_1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px" viewBox="0 0 43.9 43.9" style="enable-background:new 0 0 43.9 43.9;" xml:space="preserve">
                    <g>
                      <path d="M32.5,19.4c-0.5,0-0.9,0.2-1.3,0.7v-3H30v9.2h1.2v-0.7c0.4,0.5,0.8,0.8,1.3,0.8c0.5,0,0.8-0.3,1-0.8c0.1-0.3,0.1-0.7,0.1-1.4v-2.7c0-0.6,0-1.1-0.1-1.4C33.3,19.6,33,19.4,32.5,19.4z M32.4,24.4c0,0.6-0.2,0.9-0.5,0.9c-0.2,0-0.4-0.1-0.6-0.3v-4.2c0.2-0.2,0.4-0.3,0.6-0.3c0.4,0,0.5,0.3,0.5,0.9V24.4z"/>
                      <path d="M11.7,20.4c-0.4,0-0.6,0.3-0.6,1v2.9c0,0.6,0.2,1,0.6,1c0.4,0,0.6-0.3,0.6-1v-2.9C12.3,20.8,12.1,20.4,11.7,20.4z"/>
                      <path d="M27.7,24.7c-0.3,0.4-0.5,0.6-0.8,0.6c-0.2,0-0.3-0.1-0.3-0.3c0,0,0-0.2,0-0.5v-5h-1.2v5.4c0,0.5,0,0.8,0.1,1c0.1,0.3,0.4,0.5,0.8,0.5c0.5,0,0.9-0.3,1.4-0.8v0.7h1.2v-6.8h-1.2V24.7z"/>
                      <polygon points="20.8,18.4 22.3,18.4 22.3,26.3 23.7,26.3 23.7,18.4 25.2,18.4 25.2,17.1 20.8,17.1  "/>
                      <path d="M36.4,19.4c-0.6,0-1.1,0.2-1.5,0.7c-0.3,0.3-0.4,0.9-0.4,1.6v2.4c0,0.7,0.1,1.3,0.4,1.6c0.4,0.5,0.9,0.7,1.5,0.7c0.6,0,1.2-0.2,1.5-0.7c0.2-0.2,0.2-0.5,0.3-0.7c0-0.1,0-0.4,0-0.8v-0.2H37c0,0.5,0,0.8,0,0.8c-0.1,0.3-0.2,0.5-0.6,0.5c-0.4,0-0.6-0.3-0.6-1v-1.2h2.5v-1.4c0-0.7-0.1-1.3-0.4-1.6C37.6,19.6,37.1,19.4,36.4,19.4z M37.1,22.1h-1.2v-0.6c0-0.6,0.2-0.9,0.6-0.9c0.4,0,0.6,0.3,0.6,0.9V22.1z"/>
                      <path d="M22.4,0.5C10.6,0.5,0.9,10.1,0.9,22c0,11.9,9.6,21.5,21.5,21.5c11.9,0,21.5-9.6,21.5-21.5C43.9,10.1,34.3,0.5,22.4,0.5z M8.2,22.6v3.8H6.8v-3.8c-0.1-0.7-0.4-1.6-0.9-2.9C5.6,18.8,5.3,17.9,5,17h1.5l1,3.6L8.4,17h1.4L8.2,22.6z M13.6,24.1c0,0.7-0.1,1.3-0.4,1.6c-0.3,0.5-0.8,0.7-1.5,0.7c-0.6,0-1.1-0.2-1.5-0.7c-0.3-0.3-0.4-0.9-0.4-1.6v-2.4c0-0.7,0.1-1.3,0.4-1.6c0.3-0.5,0.8-0.7,1.5-0.7c0.6,0,1.1,0.2,1.5,0.7c0.3,0.4,0.4,0.9,0.4,1.6V24.1z M18.2,26.3h-1.3v-0.8c-0.5,0.6-1,0.8-1.4,0.8c-0.4,0-0.7-0.2-0.8-0.5c-0.1-0.2-0.1-0.5-0.1-1v-5.5h1.2v5.1c0,0.3,0,0.4,0,0.5c0,0.2,0.1,0.3,0.3,0.3c0.3,0,0.5-0.2,0.8-0.6v-5.3h1.3V26.3z M37.2,28.7C34.7,29,32.1,29,29.6,29c-2.6,0-5.1,0-7.7-0.3c-1.1-0.1-2-0.9-2.2-2c-0.4-1.6-0.4-3.3-0.4-4.9c0-1.6,0-3.3,0.4-4.9c0.2-1.1,1.1-1.9,2.2-2c2.5-0.3,5.1-0.3,7.7-0.3c2.6,0,5.1,0,7.7,0.3c1.1,0.1,2,0.9,2.2,2c0.4,1.6,0.4,3.2,0.4,4.9c0,1.6,0,3.3-0.4,4.9C39.2,27.8,38.3,28.6,37.2,28.7z"/>
                    </g>
                  </svg>
                </a>
              </li>
            </ul>
          </div>
          <div class="col-xs-12 nopadding text-center">
            <a href="#" class="security">
              <svg version="1.1" id="Capa_1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px" viewBox="0 0 43.9 43.9" style="enable-background:new 0 0 43.9 43.9;" xml:space="preserve">
                <g>
                  <polygon points="22.1,35.3 23.3,37.9 26.1,38.2 24.1,40.3 24.6,43.1 22.1,41.8 19.5,43.1 20,40.3 18,38.2 20.8,37.9  "/>
                  <polygon points="13.8,36.9 14.8,38.9 17.1,39.2 15.5,40.8 15.8,43.1 13.8,42 11.8,43.1 12.2,40.8 10.6,39.2 12.8,38.9 "/>
                  <polygon points="30.3,36.9 31.3,38.9 33.5,39.2 32,40.8 32.3,43.1 30.3,42 28.3,43.1 28.7,40.8 27.1,39.2 29.3,38.9  "/>
                  <path d="M32.3,13.7v-2.6l0,0C32.2,5.5,27.7,1,22.1,1S11.9,5.5,11.8,11.1l0,0v2.6h-2v17c0,1.3,1,2.3,2.3,2.3h20c1.3,0,2.3-1,2.3-2.3v-17L32.3,13.7z M23,24.5l0.9,3h-1.9l0,0h-1.9l0.9-3c-0.8-0.3-1.3-1.1-1.3-2c0-1.2,1-2.2,2.2-2.2s2.2,1,2.2,2.2C24.3,23.4,23.8,24.2,23,24.5L23,24.5z M29.2,13.7H14.9v-2.6l0,0c0.1-3.9,3.2-7,7.1-7s7.1,3.1,7.1,7l0,0V13.7z"/>
                </g>
              </svg>
              <span>WEBSITE SEGURO. CONEXIÓN SSL</span>
            </a>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>
<section id="copyright">
  <div class="container">
    <div class="row">
      <div class="col-xs-12 nopadding text-left text-center-xs">
        <p class="nopadding nomargin textWhite light">
          ©2018 Industrial Escowill, S.A. de C.V | 
        </p>
        <a href="#" class="nopadding nomargin light">Aviso de Privacidad</a>
      </div>
    </div>
  </div>
</section>
</body>

<!-- Latest compiled and minified JavaScript -->
<script src='https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js'></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validate/1.16.0/jquery.validate.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/scrollReveal.js/3.3.6/scrollreveal.min.js"></script>
<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyAYkMddFBx2DO9pgrHW3PG1-bT5D4_V-WE"></script>
<script src='assets/js/parallax.min.js'></script>
<script src='assets/js/slick.js'></script>
<script src='assets/js/form.js'></script>
<script src='assets/js/dev.js'></script>
</html>