<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, minimum-scale=1, maximum-scale=1">
	<link href="https://fonts.googleapis.com/css?family=Roboto:100,100i,300,300i,400,400i,500,500i,700,700i,900,900i" rel="stylesheet">
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
	<!-- Latest compiled and minified CSS -->
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
	<link rel="stylesheet" href="assets/css/hamburgers.min.css">
	<link rel="stylesheet" href="assets/css/slick.css">
	<link rel="stylesheet" href="assets/css/slick-theme.css">
	<link rel="stylesheet" href="assets/css/font.css">
	<link rel="stylesheet" href="assets/css/template.css">
	<link rel="stylesheet" href="assets/css/dev.css">
	<link href='assets/img/icon.png' rel='shortcut icon' type='image/png'>
	<title><?php if(isset($this->titulo)) echo $this->titulo; ?></title>
</head>
<body>
<div id="modalSuccess" data-izimodal-title="Muchas gracias por tu comentario" data-izimodal-subtitle="En unas horas aparecer en nuestra pagina."></div>

<div class="loaderPage">
	<div class="cSVG">
		<img src="assets/img/loader.svg" alt="">
	</div>
</div>

<section class="nopadding hidden-sm hidden-md hidden-lg" id="MenuHamburguer">
	<button class="hamburger hamburger--collapse" type="button">
	  <span class="hamburger-box">
	    <span class="hamburger-inner"></span>
	  </span>
	</button>
</section>

<section class="firstSection" id="topSection">
	<div class="container">
		<div class="row">
			<div class="col-xs-12 nopadding text-right">
				<ul class="accesos hidden-xs">
					<li>
						<a href="#">
							<img src="assets/img/user.svg" alt="">
							<span>REGISTRO</span>
						</a>
					</li>
					<li>
						<a href="#">
							<img src="assets/img/login.svg" alt="">
							<span>ACCESO</span>
						</a>
					</li>
				</ul>
				<ul class="sucursales hidden-xs">
					<span>SUCURSALES</span>
					<li>
						<a href="#">GDLJ</a>
					</li>
					<li>
						<a href="#">MTY</a>
					</li>
					<li>
						<a href="#">QRO</a>
					</li>
				</ul>
				<ul class="telefonos">
					<li>
						<a href="#">
							<img src="assets/img/tel.svg" alt="">
							<span>01 (55) 5649 8005</span>
						</a>
					</li>
				</ul>
			</div>
		</div>
	</div>
</section>

<section id="menu">
	<div class="container">
		<div class="row">
			<ul class="principal">
				<li class="logo hidden-xs hidden-sm">
					<a href="index">
						<img src="assets/img/logoTop.svg" alt="">
					</a>
				</li>
				<li class="hidden-xs">
					<a href="Productos">PRODUCTOS</a>
				</li>
				<li class="hidden-sm hidden-md hidden-lg">
					<a href="#">BOTELLAS
						<svg class="inactive" version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px" viewBox="0 0 164 164" style="enable-background:new 0 0 164 164;" xml:space="preserve">
							<path d="M32,84h48v48c0,1.1,0.9,2,2,2s2-0.9,2-2V84h48c1.1,0,2-0.9,2-2s-0.9-2-2-2H84V32c0-1.1-0.9-2-2-2s-2,0.9-2,2v48H32c-1.1,0-2,0.9-2,2S30.9,84,32,84z"/>
							<path d="M162,0H2C0.9,0,0,0.9,0,2v160c0,1.1,0.9,2,2,2h160c1.1,0,2-0.9,2-2V2C164,0.9,163.1,0,162,0z M160,160H4V4h156V160z"/>
						</svg>
						<svg class="active" version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px" viewBox="0 0 164 164" style="enable-background:new 0 0 164 164;" xml:space="preserve">
							<path d="M84,84h48c1.1,0,2-0.9,2-2s-0.9-2-2-2H84l0,0"/>
							<path d="M84,80h-4H32c-1.1,0-2,0.9-2,2s0.9,2,2,2h52"/>
							<path d="M162,0H2C0.9,0,0,0.9,0,2v160c0,1.1,0.9,2,2,2h160c1.1,0,2-0.9,2-2V2C164,0.9,163.1,0,162,0z M160,160H4V4h156V160z"/>
						</svg>
					</a>
					<ul>
						<li><a href="#">1ml - 49 ml</a></li>
						<li><a href="#">50 ml - 99 ml</a></li>
						<li><a href="#">100 ml - 199 ml</a></li>
						<li><a href="#">200 ml - 499 ml</a></li>
						<li><a href="#">500 ml - 999 ml</a></li>
						<li><a href="#">1000 ml - 1200 ml</a></li>
					</ul>
				</li>
				<li class="hidden-sm hidden-md hidden-lg">
					<a href="Productos">TARROS
						<svg class="inactive" version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px" viewBox="0 0 164 164" style="enable-background:new 0 0 164 164;" xml:space="preserve">
							<path d="M32,84h48v48c0,1.1,0.9,2,2,2s2-0.9,2-2V84h48c1.1,0,2-0.9,2-2s-0.9-2-2-2H84V32c0-1.1-0.9-2-2-2s-2,0.9-2,2v48H32c-1.1,0-2,0.9-2,2S30.9,84,32,84z"/>
							<path d="M162,0H2C0.9,0,0,0.9,0,2v160c0,1.1,0.9,2,2,2h160c1.1,0,2-0.9,2-2V2C164,0.9,163.1,0,162,0z M160,160H4V4h156V160z"/>
						</svg>
						<svg class="active" version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px" viewBox="0 0 164 164" style="enable-background:new 0 0 164 164;" xml:space="preserve">
							<path d="M84,84h48c1.1,0,2-0.9,2-2s-0.9-2-2-2H84l0,0"/>
							<path d="M84,80h-4H32c-1.1,0-2,0.9-2,2s0.9,2,2,2h52"/>
							<path d="M162,0H2C0.9,0,0,0.9,0,2v160c0,1.1,0.9,2,2,2h160c1.1,0,2-0.9,2-2V2C164,0.9,163.1,0,162,0z M160,160H4V4h156V160z"/>
						</svg>
					</a>
					<ul>
						<li><a href="#">1ml - 49 ml</a></li>
						<li><a href="#">50 ml - 99 ml</a></li>
						<li><a href="#">100 ml - 199 ml</a></li>
						<li><a href="#">200 ml - 499 ml</a></li>
						<li><a href="#">500 ml - 999 ml</a></li>
						<li><a href="#">1000 ml - 1200 ml</a></li>
					</ul>
				</li>
				<li class="hidden-sm hidden-md hidden-lg">
					<a href="Productos">TAPAS / ATOMIZADORES
						<svg class="inactive" version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px" viewBox="0 0 164 164" style="enable-background:new 0 0 164 164;" xml:space="preserve">
							<path d="M32,84h48v48c0,1.1,0.9,2,2,2s2-0.9,2-2V84h48c1.1,0,2-0.9,2-2s-0.9-2-2-2H84V32c0-1.1-0.9-2-2-2s-2,0.9-2,2v48H32c-1.1,0-2,0.9-2,2S30.9,84,32,84z"/>
							<path d="M162,0H2C0.9,0,0,0.9,0,2v160c0,1.1,0.9,2,2,2h160c1.1,0,2-0.9,2-2V2C164,0.9,163.1,0,162,0z M160,160H4V4h156V160z"/>
						</svg>
						<svg class="active" version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px" viewBox="0 0 164 164" style="enable-background:new 0 0 164 164;" xml:space="preserve">
							<path d="M84,84h48c1.1,0,2-0.9,2-2s-0.9-2-2-2H84l0,0"/>
							<path d="M84,80h-4H32c-1.1,0-2,0.9-2,2s0.9,2,2,2h52"/>
							<path d="M162,0H2C0.9,0,0,0.9,0,2v160c0,1.1,0.9,2,2,2h160c1.1,0,2-0.9,2-2V2C164,0.9,163.1,0,162,0z M160,160H4V4h156V160z"/>
						</svg>
					</a>
					<ul>
						<li><a href="#">1ml - 49 ml</a></li>
						<li><a href="#">50 ml - 99 ml</a></li>
						<li><a href="#">100 ml - 199 ml</a></li>
						<li><a href="#">200 ml - 499 ml</a></li>
						<li><a href="#">500 ml - 999 ml</a></li>
						<li><a href="#">1000 ml - 1200 ml</a></li>
					</ul>
				</li>
				<li class="hidden-sm hidden-md hidden-lg">
					<a href="Productos">FORMA / FAMILIA
						<svg class="inactive" version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px" viewBox="0 0 164 164" style="enable-background:new 0 0 164 164;" xml:space="preserve">
							<path d="M32,84h48v48c0,1.1,0.9,2,2,2s2-0.9,2-2V84h48c1.1,0,2-0.9,2-2s-0.9-2-2-2H84V32c0-1.1-0.9-2-2-2s-2,0.9-2,2v48H32c-1.1,0-2,0.9-2,2S30.9,84,32,84z"/>
							<path d="M162,0H2C0.9,0,0,0.9,0,2v160c0,1.1,0.9,2,2,2h160c1.1,0,2-0.9,2-2V2C164,0.9,163.1,0,162,0z M160,160H4V4h156V160z"/>
						</svg>
						<svg class="active" version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px" viewBox="0 0 164 164" style="enable-background:new 0 0 164 164;" xml:space="preserve">
							<path d="M84,84h48c1.1,0,2-0.9,2-2s-0.9-2-2-2H84l0,0"/>
							<path d="M84,80h-4H32c-1.1,0-2,0.9-2,2s0.9,2,2,2h52"/>
							<path d="M162,0H2C0.9,0,0,0.9,0,2v160c0,1.1,0.9,2,2,2h160c1.1,0,2-0.9,2-2V2C164,0.9,163.1,0,162,0z M160,160H4V4h156V160z"/>
						</svg>
					</a>
					<ul>
						<li><a href="#">1ml - 49 ml</a></li>
						<li><a href="#">50 ml - 99 ml</a></li>
						<li><a href="#">100 ml - 199 ml</a></li>
						<li><a href="#">200 ml - 499 ml</a></li>
						<li><a href="#">500 ml - 999 ml</a></li>
						<li><a href="#">1000 ml - 1200 ml</a></li>
					</ul>
				</li>
				<li>
					<a href="#">CATÁLOGOS</a>
				</li>
				<li>
					<a href="#">NOSOTROS</a>
				</li>
				<li>
					<a href="#">CLIENTES</a>
				</li>
				<li>
					<a href="#">ESQUEMAS DE VENTA</a>
				</li>
				<li class="search hidden-xs">
					<a href="#">
						<img src="assets/img/search.svg" alt="">
					</a>
				</li>
				<li class="cart hidden-xs">
					<a href="#">
						<img src="assets/img/cart.svg" alt="">
						<span>(1)</span>
					</a>
				</li>
			</ul>
		</div>
	</div>
</section>