<section id="slide" class="firstSection">
	<div class="container">
		<div class="row">
			<div class="col-xs-12 nopadding reverse-xs">
				<div class="col-xs-12 col-md-4">
					<div class="col-xs-12 nopadding hidden-xs hidden-sm">
						<img src="assets/img/logoW.svg" alt="" class="col-xs-12 logoW pull-right">
					</div>
					<h1 class="col-xs-12 nopadding textBlue semi-bold text-right text-center-xs">SOMOS EL FABRICANTE DE BOTELLAS DE PET CON EL CATÁLOGO MÁS GRANDE DE MÉXICO</h1>
					<h3 class="col-xs-12 nopadding regular text-right hidden-xs">Más de 200 modelos de línea a tu disposición</h3>
				</div>
				<div class="col-xs-12 col-md-8">
					<img src="assets/img/home.png" alt="" class="col-xs-12 col-lg-11 nopadding centered">
				</div>
			</div>
		</div>
	</div>
</section>

<section id="EsquemasVenta" class="nopaddingTop">
	<div class="container">
		<div class="row">
			<div class="col-xs-12 noHorizontalPadding vxpadding nopaddingTop hidden-xs">
				<h1 class="col-xs-12 nopadding textBlue semi-bold text-left">ESQUEMAS DE VENTA <small>Nos acoplamos a tus planes con nuestros 3 esquemas de venta</small></h1>
			</div>
			<div class="col-xs-12 nopadding">
				<div class="col-xs-12 col-sm-4 item noHorizontalPadding vxpadding nopaddingTop text-center">
					<div class="centered col-xs-12 nopadding text-left">
						<div class="col-xs-12 nopadding image">
							<img src="assets/img/esquemas/1.jpg" alt="">
							<div class="vertical">
								<h2 class="col-xs-12 textWhite text-center regular">STOCK PERMANENTE</h2>
							</div>
						</div>
						<p class="col-xs-12 nomargin vpadding nopaddingBottom text-justify">En nuestro almacén de stock permanente tenemos siempre  a tu disposición nuestros modelos de mayor demanda.</p>
						<a href="#" class="btnStyle1 pull-right">
							<div></div>
							<span>LEER MÁS</span>
						</a>
					</div>
				</div>
				<div class="col-xs-12 col-sm-4 item noHorizontalPadding vxpadding nopaddingTop text-center">
					<div class="centered col-xs-12 nopadding text-left">
						<div class="col-xs-12 nopadding image">
							<img src="assets/img/esquemas/2.jpg" alt="">
							<div class="vertical">
								<h2 class="col-xs-12 textWhite text-center regular">VENTAS BAJO PEDIDO</h2>
							</div>
						</div>
						<p class="col-xs-12 nomargin vpadding nopaddingBottom text-justify">Bajo pedido podemos fabricar cualquier  modelo de este catálogo en color cristal o en cualquier color de nuestra gama, con mínimos de venta accesibles y los mejores tiempos de entrega.</p>
						<a href="#" class="btnStyle1 pull-right">
							<div></div>
							<span>LEER MÁS</span>
						</a>
					</div>
				</div>
				<div class="col-xs-12 col-sm-4 item noHorizontalPadding vxpadding nopaddingTop text-center">
					<div class="centered col-xs-12 nopadding text-left">
						<div class="col-xs-12 nopadding image">
							<img src="assets/img/esquemas/3.jpg" alt="">
							<div class="vertical">
								<h2 class="col-xs-12 textWhite text-center regular">DESARROLLOS ESPECIALES</h2>
							</div>
						</div>
						<p class="col-xs-12 nomargin vpadding nopaddingBottom text-justify">Si tu idea es crear una forma de envase totalmente nueva,  un envase personalizado y exclusivo, tenemos un equipo experimentado  de ingenieros y diseñadores y un taller de moldes propio para convertir esta idea en un envase en tiempo y costos competitivos.</p>
						<a href="#" class="btnStyle1 pull-right">
							<div></div>
							<span>LEER MÁS</span>
						</a>
					</div>
				</div>
			</div>
		</div>
	</div>
</section>